# f = open("demo.txt","rt")
# print(f.read())
# f = open("D:\\demo.txt","rt")
# print(f.read())
# f = open("demo.txt","rt")
# print(f.read(5))
# f = open("demo.txt","rt")
# print(f.readline())
# print(f.readline())
# f = open("demo.txt","rt")
# for x in f:
#     print(x)
# f = open("demo.txt","rt")
# print(f.readline())
# f.close()
# f = open("demo.txt","a")
# f.write("Massmatic is under the ages of Akhil Bhartiya Cyber Suraksha Sangathan")
# f.close()
# f = open("demo.txt","rt")
# print(f.read())
# f.close()
# f = open("demo.txt","w")
# f.write("Massmatic is under the ages of Akhil Bhartiya Cyber Suraksha Sangathan")
# f.close()
# f = open("demo.txt","rt")
# print(f.read())
# f = open("demo2.txt","x")
# f.write("We are creating a new file")
# f.close()
# f = open("demo2.txt","r")
# print(f.read())
# import os
# os.remove("demo2.txt")
# import os
# if os.path.exists("demo2.txt"):
#     os.remove("demo2.txt")
# else:
#     print("This file does not exists.")
import os
os.rmdir("test")
